version: 2
updates:
# Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
      timezone: "UTC"
    cooldown:
      default-days: 7
    groups:
      actions:
        patterns:
          - "*"
