name: Setup Artifactory
author: Payton Leedham
inputs:
  username:
    description: Artifactory username
    required: false  # Note `required` doesn't actually do anything: https://github.com/actions/runner/issues/1070
    default: ${{ env.ART_USER }}

  api-key:
    description: Artifactory API key
    required: true
    default: ${{ env.ART_KEY }}

runs:
  using: "composite"
  steps:
    - name: Create netrc file
      shell: bash
      run: |
        echo "machine metoffice.jfrog.io" >> ~/.netrc
        # If username is empty don't add login entry to .netrc (assumes Access Token):
        if [[ -s ${{ inputs.username }} ]]; then
          echo "[DEBUG] USERNAME: '${{ inputs.username}}'"
          echo "  login ${{ inputs.username }}" >> ~/.netrc
        fi
        echo "  password ${{ inputs.api-key }}" >> ~/.netrc

    - name: Add the conda channel_alias for Artifactory
      shell: bash
      run: |
        CHANNEL_ALIAS_STR="channel_alias: https://metoffice.jfrog.io/metoffice/api/conda"

        if grep "^channel_alias" ~/.condarc 2>/dev/null; then
            echo "INFO: channel_alias already present in ~/.condarc"
        else
            echo "INFO: Adding channel_alias to ~/.condarc"
            echo ${CHANNEL_ALIAS_STR} >> ~/.condarc
        fi

    - name: Create pip file
      shell: bash
      run: |
        mkdir -p ~/.config/pip
        cat << EOF > ~/.config/pip/pip.conf
        [global]
        index-url = https://metoffice.jfrog.io/metoffice/api/pypi/pypi/simple
        trusted-host = metoffice.jfrog.io
        EOF
