name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-no-default:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    env:
      ART_USER: ${{ secrets.art_user }}
      ART_KEY: ${{ secrets.art_key }}
    steps:
      - name: Run action
        #uses: MetOffice/action-setup-artifactory@main
        uses: MetOffice/action-setup-artifactory@optional_username
        with:
          username: $ART_USER
          api-key: $ART_KEY

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Package
        run: pip install cloudteam-pythontools

  test-use-defaults:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    env:
      ART_USER: ${{ secrets.art_user }}
      ART_KEY: ${{ secrets.art_key }}
    steps:
      - name: Run action
        #uses: MetOffice/action-setup-artifactory@main
        uses: MetOffice/action-setup-artifactory@optional_username


      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Package
        run: pip install cloudteam-pythontools

  test-no-username:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    env:
      ART_TOKEN: "this_is_an_access_token_no_username_required"
    steps:
      - name: Run action
        #uses: MetOffice/action-setup-artifactory@main
        uses: MetOffice/action-setup-artifactory@optional_username
        with:
          api-key: ${{ env.ART_TOKEN }}

      - name: Debug netrc
        shell: bash
        run: |
          echo "Contents of netrc file:"
          echo "---------------------------------------"
          cat ~/.netrc
          echo "---------------------------------------"

      - name: Assert netrc correct
        shell: bash
        run: |
          if (( $(cat ~/.netrc | wc -l) != 2 )); then
            echo "Wrong number of lines in .netrc file!";
            exit 1
          fi
          
          if grep "\<login\>" ~/.netrc; then
            echo "Unexpected 'login' entry found in ~/.netrc file."
            exit 1;
          fi
          
          if ! grep -e "machine metoffice.jfrog.io" ~/.netrc; then
            echo "Missing correct 'machine' field from ~/.netrc file."
          fi

          if ! grep -e "\<password\> *${{ env.ART_TOKEN }}" ~/.netrc; then
            echo "Missing correct 'password' field from ~/.netrc file."
          fi

#      - name: Setup Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: "3.8"
#
#      - name: Install Package
#        run: pip install cloudteam-pythontools
