name: Test
on:
  push:
    branches:
      - main

jobs:
  test-with-check-creds:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Run action
        uses: MetOffice/action-setup-artifactory@main
        with:
          check-creds: true
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Package
        run: pip install cloudteam-pythontools

  test-no-defaults:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Run action
        uses: MetOffice/action-setup-artifactory@main
        with:
          username: ${{ secrets.art_user }}
          api-key: ${{ secrets.art_key }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Package
        run: pip install cloudteam-pythontools
